.TH CV 1 "September 01, 2014" "cv"

.SH NAME
cv \- Coreutils Viewer
.SH SYNOPSIS
.B cv
.I [-vqwmMh] [-W] [-c command]
.br

.SH DESCRIPTION
This manual page briefly documents the \fBcv\fP command.
.PP
This tool can be described as a Tiny Dirty Linux Only* C command that looks for coreutils basic
commands (cp, mv, dd, tar, gzip/gunzip, cat, ...) currently running on your system and displays
the percentage of copied data.

It can now also display an estimated throughput (using -w flag).

.SH OPTIONS
.TP
.B \-v (\-\-version)
show version
.TP
.B \-q (\-\-quiet)
hides all messages
.TP
.B \-d (\-\-debug)
shows all warning/error messages
.TP
.B \-w (\-\-wait)
estimate I/O throughput and ETA (slower display)
.TP
.B \-W (\-\-wait\-delay secs)
wait 'secs' seconds for I/O estimation (implies -w)
.TP
.B \-m (\-\-monitor)
loop while monitored processes are still running
.TP
.B \-M (\-\-monitor\-continous)
like monitor but never stop (similar to watch cv)
.TP
.B \-h (\-\-help)
this message
.TP
.B \-c (\-\-command cmd)
monitor only this command name (ex: firefox)

.SH BUGS
Please report bugs at: http://github.com/Xfennec/cv/issues

.SH HOMEPAGE
http://github.com/Xfennec/cv

.SH AUTHOR
This manual page was written by Thomas Zimmermann <bugs@vdm-design.de>,
for the openSUSE project (and may be used by others).
