.TH PROGRESS 1 "January 22, 2016" "progress"

.SH NAME
progress \- Coreutils Progress Viewer
.SH SYNOPSIS
.B progress
[
.B \-qdwmM
] [
.B \-W
.I secs
] [
.B \-c
.I command
] [
.B \-a
.I command
] [
.B \-p
.I pid
]
.br
.B progress -v
|
.B \-\-version
.br
.B progress \-h
|
.B \-\-help
.br

.SH DESCRIPTION
This manual page briefly documents the \fBprogress\fP command.
.PP
This tool can be described as a Tiny, Dirty, Linux-Only C command
that looks for coreutils basic commands (cp, mv, dd, tar, gzip/gunzip,
cat, etc.) currently running on your system and displays the
percentage of copied data.

It can now also estimate throughput (using flag
.BR \-w ).

.SH OPTIONS
.TP
.B \-q (\-\-quiet)
hides all messages
.TP
.B \-d (\-\-debug)
shows all warning/error messages
.TP
.B \-w (\-\-wait)
estimate I/O throughput and estimated remaining time (slower display)
.TP
.B \-W (\-\-wait\-delay secs)
wait 'secs' seconds for I/O estimation (implies
.BR \-w )
.TP
.B \-m (\-\-monitor)
loop while monitored processes are still running
.TP
.B \-M (\-\-monitor\-continuously)
like monitor but never stop (similar to
.BR "watch progress" )
.TP
.B \-c (\-\-command cmd)
monitor only this command name (ex: firefox). This option can be used multiple
times on the command line.
.TP
.B \-a (\-\-additional-command cmd)
add this command to the default list. This option can be used multiple
times on the command line.
.TP
.B \-p (\-\-pid id)
monitor only this numeric process ID (ex: \`pidof firefox\`). This option can
be used multiple times on the command line.
.TP
.B \-i (\-\-ignore-file file)
do not report a process for 'file'. If the file does not exist yet, you must
give a full and clean absolute path. This option can be used multiple times
on the command line.
.TP
.B \-o (\-\-open-mode {r|w})
report only files opened for read or write by the process. This option is
useful when you want to monitor only output files (or input ones) of a process.
.TP
.B \-v (\-\-version)
show program version and exit
.TP
.B \-h (\-\-help)
display help message and exit

.SH ENVIRONMENT
It's possible to give permanent options using PROGRESS_ARGS environment variable.
See example below. Command line arguments take precedence over environment.

.SH EXAMPLES

Continuously monitor all current and upcoming instances of coreutils commands
.RS

.B watch progress \-q

.RE
See how your download is progressing
.RS

.B watch progress \-wc firefox

.RE
Look at your Web server activity
.RS

.B progress \-c httpd

.RE
Launch and monitor any heavy command using $!
.RS

.B cp bigfile newfile & progress \-mp $!


.RE
Use environment variable to set permanent (multiple) arguments
.RS

.B export PROGRESS_ARGS='-M \-\-ignore-file ~/.xsession-errors'

.RE
.SH BUGS
Please report bugs at: http://github.com/Xfennec/progress/issues

.SH HOMEPAGE
http://github.com/Xfennec/progress

.SH AUTHOR
This manual page was written by Thomas Zimmermann <bugs@vdm-design.de>,
for the openSUSE project (and may be used by others).
